name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    name: Install Root Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install all dependencies (root + workspaces)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Lint backend
        run: npm run lint --workspace backend

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint --workspace frontend

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: [lint-backend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Build backend
        run: npm run build --workspace backend

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Build frontend
        run: npm run build --workspace frontend
